# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Genapp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Genapp
  pod 'GRMustache.swift'
  
  target 'GenappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GenappUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
